import os

ALLOWED_FILE_EXTENSIONS_ENV_KEY = "ALLOWED_FILE_EXTENSIONS"
DEFAULT_FROM_FILE_EXTENSION_ENV_KEY = "DEFAULT_FROM_FILE_EXTENSION"
DEFAULT_TO_FILE_EXTENSION_ENV_KEY = "DEFAULT_TO_FILE_EXTENSION"
EXTENSION_SAME_ERROR_MESSAGEE = "The extensions can't be same!"